apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  selector:
    app: catalog
  ports:
  - port: 80
    targetPort: 5000

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog-serviceaccount
  annotations:
    azure.workload.identity/client-id: 99030de5-71eb-41e5-b1b4-3bd3d753f969
  labels:
    azure.workload.identity/use: "true"